export const defaultConfig = {
  gridSize: 10,
  maxDotSize: 40,
  minDotSize: 0,
  dotColorHex: "#000000",
  dotOpacity: 0.3,
  brightnessMin: 0,
  brightnessMax: 255,
  animationDuration: 1.5,
  animationEase: "circ.out",
  invertMode: true,
  dotShape: "circle",
  transitionMode: "exit-enter",
  staggerType: "center-out",
  staggerAmount: 0.4,
};

export const scenarios = {
  pastime: {
    ...defaultConfig,
  },
  newsprint: {
    ...defaultConfig,
    gridSize: 6,
    maxDotSize: 24,
    minDotSize: 0,
    dotOpacity: 0.1,
    dotColorHex: "#1a1a1a",
    animationDuration: 0.9,
    animationEase: "power2.out",
    transitionMode: "morph",
    staggerType: "none",
    staggerAmount: 0,
    dotShape: "circle",
  },
  diamonds: {
    ...defaultConfig,
    dotShape: "diamond",
    gridSize: 14,
    maxDotSize: 56,
    minDotSize: 2,
    dotOpacity: 0.3,
    animationDuration: 1.2,
    animationEase: "expo.out",
    transitionMode: "exit-enter",
    staggerType: "wave",
    staggerAmount: 0.5,
  },
  "rapid fire": {
    ...defaultConfig,
    animationDuration: 0.4,
    animationEase: "power4.out",
    transitionMode: "exit-enter",
    staggerType: "left-right",
    staggerAmount: 0.6,
    dotShape: "square",
    gridSize: 8,
    maxDotSize: 32,
    dotOpacity: 0.5,
  },
  "slow burn": {
    ...defaultConfig,
    animationDuration: 1.5,
    animationEase: "circ.out",
    transitionMode: "morph",
    staggerType: "random",
    staggerAmount: 0.8,
    dotShape: "circle",
    gridSize: 12,
    maxDotSize: 50,
    dotOpacity: 0.3,
  },
  enhance: {
    ...defaultConfig,
    animationDuration: 1,
    animationEase: "circ.out",
    transitionMode: "morph",
    staggerType: "random",
    staggerAmount: 0.95,
    dotShape: "x",
    gridSize: 12,
    maxDotSize: 50,
    dotOpacity: 0.3,
  },
  snapshot: {
    ...defaultConfig,
    animationDuration: 1,
    animationEase: "circ.out",
    transitionMode: "morph",
    staggerType: "random",
    staggerAmount: 0.95,
    dotShape: "x",
    gridSize: 12,
    maxDotSize: 50,
    dotOpacity: 0.3,
  },
  stars: {
    ...defaultConfig,
    dotShape: "star",
    gridSize: 18,
    maxDotSize: 72,
    minDotSize: 4,
    dotOpacity: 0.55,
    animationDuration: 1.8,
    animationEase: "back.out",
    transitionMode: "exit-enter",
    staggerType: "center-out",
    staggerAmount: 0.45,
  },
};
