export const teams = [
  {
    name: "Diamondbacks",
    color: "#A71930",
    logo: "/assets/logos/diamondbacks.svg",
    playerImage: "/assets/players/diamondbacks/carroll.jpeg",
    players: [
      "PERDOMO",
      "MARTE",
      "CARROLL",
      "MORENO",
      "ARENADO",
      "SANTANA",
      "DEL CASTILLO",
      "LAWLAR",
      "THOMAS",
    ],
  },
  {
    name: "Rockies",
    color: "#33006F",
    logo: "/assets/logos/rockies.svg",
    playerImage: "/assets/players/rockies/moniak.jpeg",
    players: [
      "TOVAR",
      "MONIAK",
      "GOODMAN",
      "BECK",
      "JOHNSTON",
      "DOYLE",
      "CASTRO",
      "MCCARTHY",
      "JULIEN",
    ],
  },
  {
    name: "Dodgers",
    color: "#005A9C",
    logo: "/assets/logos/dodgers.svg",
    playerImage: "/assets/players/dodgers/ohtani.jpeg",
    players: [
      "OHTANI",
      "TUCKER",
      "BETTS",
      "FREEMAN",
      "SMITH",
      "MUNCY",
      "HERNÁNDEZ",
      "PAGES",
      "EDMAN",
    ],
  },
  {
    name: "Padres",
    color: "#2F241D",
    logo: "/assets/logos/padres.svg",
    playerImage: "/assets/players/padres/bogaerts.jpeg",
    players: [
      "BOGAERTS",
      "MERRILL",
      "MACHADO",
      "TATIS JR",
      "CRONENWORTH",
      "LAUREANO",
      "SHEETS",
      "ANDUJAR",
      "FERMIN",
    ],
  },
  {
    name: "Giants",
    color: "#FD5A1E",
    logo: "/assets/logos/giants.svg",
    playerImage: "/assets/players/giants/devers.jpeg",
    players: [
      "ARRAEZ",
      "BADER",
      "ADAMES",
      "DEVERS",
      "CHAPMAN",
      "RAMOS",
      "ELDRIDGE",
      "LEE",
      "BAILEY",
    ],
  },
];
