export const teams = [
  {
    name: "Diamondbacks",
    color: "#A71930",
    logo: "/assets/logos/diamondbacks.svg",
    playerImage: "/assets/players/diamondbacks/carroll.jpeg",
    players: [
      { name: "Geraldo Perdomo", position: "SS", playerImage: null },
      { name: "Ketel Marte", position: "2B", playerImage: null },
      {
        name: "Corbin Carroll",
        position: "LF",
        playerImage: "/assets/players/diamondbacks/carroll.jpeg",
      },
      { name: "Gabriel Moreno", position: "C", playerImage: null },
      { name: "Nolan Arenado", position: "3B", playerImage: null },
      { name: "Carlos Santana", position: "1B", playerImage: null },
      { name: "Tomás Del Castillo", position: "C", playerImage: null },
      { name: "Jordan Lawlar", position: "SS", playerImage: null },
      { name: "Alek Thomas", position: "CF", playerImage: null },
    ],
  },
  {
    name: "Rockies",
    color: "#33006F",
    logo: "/assets/logos/rockies.svg",
    playerImage: "/assets/players/rockies/moniak.jpeg",
    players: [
      { name: "Ezequiel Tovar", position: "SS", playerImage: null },
      {
        name: "Mickey Moniak",
        position: "CF",
        playerImage: "/assets/players/rockies/moniak.jpeg",
      },
      { name: "Hunter Goodman", position: "RF", playerImage: null },
      { name: "David Beck", position: "3B", playerImage: null },
      { name: "Sean Johnston", position: "2B", playerImage: null },
      { name: "Brenton Doyle", position: "CF", playerImage: null },
      { name: "Elias Castro", position: "C", playerImage: null },
      { name: "Jake McCarthy", position: "LF", playerImage: null },
      { name: "Edouard Julien", position: "DH", playerImage: null },
    ],
  },
  {
    name: "Dodgers",
    color: "#005A9C",
    logo: "/assets/logos/dodgers.svg",
    playerImage: "/assets/players/dodgers/ohtani.jpeg",
    players: [
      {
        name: "Shohei Ohtani",
        position: "DH",
        playerImage: "/assets/players/dodgers/ohtani.jpeg",
      },
      { name: "Kyle Tucker", position: "RF", playerImage: null },
      { name: "Mookie Betts", position: "RF", playerImage: null },
      { name: "Freddie Freeman", position: "1B", playerImage: null },
      { name: "Will Smith", position: "C", playerImage: null },
      { name: "Max Muncy", position: "3B", playerImage: null },
      { name: "Kiké Hernández", position: "2B", playerImage: null },
      { name: "Andy Pages", position: "LF", playerImage: null },
      { name: "Tommy Edman", position: "SS", playerImage: null },
    ],
  },
  {
    name: "Padres",
    color: "rgb(255, 196, 37)",
    logo: "/assets/logos/padres.svg",
    playerImage: "/assets/players/padres/bogaerts.jpeg",
    players: [
      {
        name: "Xander Bogaerts",
        position: "SS",
        playerImage: "/assets/players/padres/bogaerts.jpeg",
      },
      { name: "Jackson Merrill", position: "CF", playerImage: null },
      { name: "Manny Machado", position: "3B", playerImage: null },
      { name: "Fernando Tatis Jr.", position: "RF", playerImage: null },
      { name: "Jake Cronenworth", position: "2B", playerImage: null },
      { name: "Ramon Laureano", position: "LF", playerImage: null },
      { name: "Gavin Sheets", position: "1B", playerImage: null },
      { name: "Miguel Andújar", position: "DH", playerImage: null },
      { name: "Freddy Férmín", position: "C", playerImage: null },
    ],
  },
  {
    name: "Giants",
    color: "#FD5A1E",
    logo: "/assets/logos/giants.svg",
    playerImage: "/assets/players/giants/devers.jpeg",
    players: [
      {
        name: "Luis Arraez",
        position: "2B",
        playerImage: "/assets/players/giants/arraez.jpeg",
      },
      {
        name: "Harrison Bader",
        position: "CF",
        playerImage: "/assets/players/giants/bader.jpeg",
      },
      {
        name: "Willy Adames",
        position: "SS",
        playerImage: "/assets/players/giants/adames.jpeg",
      },
      {
        name: "Rafael Devers",
        position: "3B",
        playerImage: "/assets/players/giants/devers.jpeg",
      },
      {
        name: "Matt Chapman",
        position: "1B",
        playerImage: "/assets/players/giants/chapman.jpeg",
      },
      {
        name: "Heliot Ramos",
        position: "RF",
        playerImage: "/assets/players/giants/ramos.jpeg",
      },
      {
        name: "Bryce Eldridge",
        position: "LF",
        playerImage: "/assets/players/giants/eldridge.jpeg",
      },
      {
        name: "Jung Hoo Lee",
        position: "LF",
        playerImage: "/assets/players/giants/lee.jpeg",
      },
      {
        name: "Patrick Bailey",
        position: "C",
        playerImage: "/assets/players/giants/bailey.jpeg",
      },
    ],
  },
];
